feat: add validation step for API name input in workflows

diff --git a/.github/workflows/call_opex_api.yaml b/.github/workflows/call_opex_api.yaml
--- a/.github/workflows/call_opex_api.yaml
+++ b/.github/workflows/call_opex_api.yaml
@@ -37,6 +37,16 @@ jobs:
         with:
           persist-credentials: false
           fetch-depth: 0
+      
+      - name: Validate Inputs API Name
+        id: validate_inputs_api_name
+        shell: bash
+        run: |
+          TARGET_DIR=".opex/${{ inputs.api_name }}"
+          if [ ! -d "$TARGET_DIR" ]; then
+            echo "Invalid api_name '${{ inputs.api_name }}'. Directory $TARGET_DIR does not exist."
+            exit 1
+          fi
 
       - uses: pagopa/opex-dashboard-azure-action@ece3bc2b133be74cabb50aec14cdb9b8051b886f # action v1.1.2
         with:
diff --git a/.github/workflows/call_pr_opex_api.yaml b/.github/workflows/call_pr_opex_api.yaml
--- a/.github/workflows/call_pr_opex_api.yaml
+++ b/.github/workflows/call_pr_opex_api.yaml
@@ -38,6 +38,16 @@ jobs:
           persist-credentials: false
           fetch-depth: 0
 
+      - name: Validate Inputs API Name
+        id: validate_inputs_api_name
+        shell: bash
+        run: |
+          TARGET_DIR=".opex/${{ inputs.api_name }}"
+          if [ ! -d "$TARGET_DIR" ]; then
+            echo "Invalid api_name '${{ inputs.api_name }}'. Directory $TARGET_DIR does not exist."
+            exit 1
+          fi
+
       - name: Azure Login
         id: az_login
         uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
